"""empty message

Revision ID: c783aec67cf3
Revises: 00043145c3c9
Create Date: 2024-11-04 22:41:18.945457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c783aec67cf3'
down_revision: Union[str, None] = '00043145c3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bet', sa.Column('status', sa.String(), nullable=False))
    op.add_column('bet', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bet', 'updated_at')
    op.drop_column('bet', 'status')
    # ### end Alembic commands ###
